# Generated by Django 4.2.4 on 2023-08-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customerpurchase_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerPurchase',
        ),
    ]
