# Generated by Django 4.2.4 on 2023-08-11 11:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0007_alter_customer_checkid_and_more'),
        ('core', '0003_delete_customerpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name="To'lov Sanasi")),
                ('amount', models.FloatField(verbose_name='Summa')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='authapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Summa')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('customerPurchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financies', to='authapp.customerpurchase')),
            ],
        ),
    ]
