# Generated by Django 4.2.4 on 2023-08-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_customerpurchase_financialstatus_productpurchase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialstatus',
            options={'verbose_name': 'Finance', 'verbose_name_plural': 'Finances'},
        ),
    ]
