# Generated by Django 4.2.4 on 2023-08-10 15:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_remove_customer_is_active_remove_customer_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='checkId',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, verbose_name='Check Id'),
        ),
        migrations.CreateModel(
            name='CustomerPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255, verbose_name='Maxsulot nomi')),
                ('costProduct', models.FloatField(verbose_name='Maxsulot tan narxi')),
                ('startingFee', models.FloatField(default=0.0, verbose_name="Boshlang'ich to'lov")),
                ('taxRate', models.FloatField(verbose_name='Soliq foizi')),
                ('paymentDay', models.IntegerField(default=15, verbose_name="To'lov kuni")),
                ('amountOfMonth', models.FloatField(blank=True, null=True, verbose_name='Oylik tolov')),
                ('totalPrice', models.FloatField(blank=True, null=True, verbose_name='Ummumiy summa')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('startedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlanish sanasi')),
                ('finishedAt', models.DateTimeField(verbose_name='Tugash sanasi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.customer')),
            ],
            options={
                'verbose_name': 'Maxsulot',
                'verbose_name_plural': 'Maxsulotlar',
            },
        ),
    ]
