# Generated by Django 4.2.4 on 2023-08-11 11:54

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_customer_options_alter_customer_checkid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='checkId',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, verbose_name='Check Id'),
        ),
        migrations.AlterField(
            model_name='customerpurchase',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='authapp.customer'),
        ),
    ]
