# Generated by Django 4.2.4 on 2023-08-11 14:04

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_customerpurchase_financialstatus_productpurchase_and_more'),
        ('authapp', '0010_customerpurchase_nextpaymentamount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerPurchase',
            new_name='ProductPurchase',
        ),
        migrations.AlterField(
            model_name='customer',
            name='checkId',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, verbose_name='Check Id'),
        ),
    ]
