# Generated by Django 4.2.4 on 2023-08-11 15:32

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_rename_customerpurchase_productpurchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='left',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qoldi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='checkId',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, verbose_name='Check Id'),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Davomiyligi'),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='nextPaymentAmount',
            field=models.FloatField(blank=True, null=True, verbose_name="Keyingi to'lov summasi"),
        ),
    ]
