# Generated by Django 4.2.4 on 2023-08-12 11:35

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_alter_customer_checkid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ochiq'), ('CLOSE', 'Yopiq')], default='OPEN', max_length=5, verbose_name='Xisob'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='checkId',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, verbose_name='Check Id'),
        ),
    ]
